# Split & Connectivity
CONFIG_ZMK_SPLIT=y
CONFIG_ZMK_SPLIT_BLE=y

# XIAO BLE Clock Stability
CONFIG_CLOCK_CONTROL_NRF_K32SRC_RC=y

# Bluetooth Stability & Signal Tuning
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y

# Power Management
CONFIG_ZMK_SLEEP=y
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=600000

# Features
CONFIG_ZMK_MOUSE=y
CONFIG_ZMK_POINTING=y
