# Enable NFC Pins (D7) as GPIOs for XIAO BLE
CONFIG_NFCT_PINS_AS_GPIOS=y

# Enable Split Mode & Bluetooth
CONFIG_ZMK_SPLIT=y
CONFIG_ZMK_SPLIT_BLE=y
CONFIG_ZMK_BLE=y
CONFIG_ZMK_USB=y

# Internal Oscillator for XIAO BLE Stability
CONFIG_CLOCK_CONTROL_NRF_K32SRC_RC=y

# Power Management
CONFIG_ZMK_SLEEP=y
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=600000
CONFIG_ZMK_PM_SOFT_OFF=y
CONFIG_GPIO=y

# Bluetooth Stability & Signal Strength
CONFIG_ZMK_BLE_PASSKEY_ENTRY=n
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y
CONFIG_ZMK_BLE_EXPERIMENTAL_FEATURES=y

# Enable Mouse Keys & Pointing
CONFIG_ZMK_MOUSE=y
CONFIG_ZMK_POINTING=y
