# Enable BLE status LED indicators
CONFIG_ZMK_BLE=y
CONFIG_GPIO=y

# Enable Split Mode (Right = Peripheral)
CONFIG_ZMK_SPLIT=y
CONFIG_ZMK_SPLIT_BLE=y

# Deep Sleep Timeout (10 mins)
CONFIG_ZMK_SLEEP=y
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=600000

# Boost transmit power to ensure rock-solid connection to the Left half
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y
